version: '3.8'

services:
  frontend:
    image: toinouu/docnote-front:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8055
    depends_on:
      - directus

  db:
    image: postgres:15
    container_name: directus_db
    restart: always
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - directus_db_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    volumes:
      - ./directus/schema:/directus/schema
    env_file:
      - ./directus/directus.env
    depends_on:
      - db
    entrypoint: >
      sh -c "
        if [ ! -f ./directus.config.js ]; then
          npx directus init;
        fi &&
        npx directus bootstrap &&
        npx directus schema apply /directus/schema/schema.yaml &&
        npx directus start
      "

volumes:
  directus_db_data:
