services:
  frontend:
    image: toinouu/docnote-front:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8055
    depends_on:
      - directus

  db:
    image: postgres:15
    container_name: directus_db
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: directus
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
    volumes:
      - directus_db_data:/var/lib/postgresql/data

  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    volumes:
      - ./directus/schema:/directus/schema
      - ./directus/directus.config.js:/directus/directus.config.js
    env_file:
      - ./directus/directus.env
    depends_on:
      - db
    entrypoint: >
      sh -c "
      npx directus bootstrap &&
      npx directus schema apply /directus/schema/schema.yaml --yes &&
      npx directus start
      "

volumes:
  directus_db_data:
