version: 1
directus: 11.8.0
vendor: postgres
collections:
  - collection: note
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: null
      archive_value: null
      collapse: open
      collection: note
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: null
      versioning: false
    schema:
      name: note
fields:
  - collection: note
    field: id
    type: integer
    meta:
      collection: note
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: note
      data_type: integer
      default_value: nextval('note_id_seq'::regclass)
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: true
      foreign_key_table: null
      foreign_key_column: null
  - collection: note
    field: title
    type: string
    meta:
      collection: note
      conditions: null
      display: null
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: title
      table: note
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: note
    field: created_at
    type: dateTime
    meta:
      collection: note
      conditions: null
      display: null
      display_options: null
      field: created_at
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: created_at
      table: note
      data_type: timestamp without time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: note
    field: content
    type: text
    meta:
      collection: note
      conditions: null
      display: null
      display_options: null
      field: content
      group: null
      hidden: false
      interface: input-multiline
      note: null
      options: null
      readonly: false
      required: false
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: content
      table: note
      data_type: text
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations: []
